[package]
name = "simple-pcf"
version = "0.1.1"
edition = "2021"
license = "MIT"
authors = ["Jayshua Nelson <me@jayshuanelson.com>"]
repository = "https://github.com/Jayshua/simple-pcf"
description = "A simple library for parsing PCF bitmap font files."

[dependencies]
